name: stale

on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  stale:
    runs-on: ubuntu-latest
    if: github.repository == 'polyaxon/polyaxon'
    steps:
    - uses: actions/stale@v4
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: 'This issue has not seen any recent activity.'
        stale-pr-message: 'This pull request has not seen any recent activity.'
        days-before-stale: 30
        days-before-close: -1
        stale-issue-label: 'stale'
        stale-pr-label: 'stale'
        exempt-issue-labels: 'no-stale,planned,roadmap,housekeeping'
        exempt-pr-labels: 'no-stale,wip'
